# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Direction": "01_direction.ipynb",
         "ToyRobot": "02_robot.ipynb",
         "Table": "02_robot.ipynb",
         "get_direction_idx": "03_main.ipynb",
         "run": "03_main.ipynb"}

modules = ["direction.py",
           "robot.py",
           "main.py"]

doc_url = "https://amaarora.github.io/toyrobot/"

git_url = "https://github.com/amaarora/toyrobot/tree/master/"

def custom_doc_links(name): return None
