# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb",
         "Direction": "01_direction.ipynb",
         "ToyRobot": "02_robot.ipynb"}

modules = ["core.py",
           "direction.py",
           "robot.py"]

doc_url = "https://amaarora.github.io/toyrobot/"

git_url = "https://github.com/amaarora/toyrobot/tree/master/"

def custom_doc_links(name): return None
