# AUTOGENERATED! DO NOT EDIT! File to edit: 01_direction.ipynb (unless otherwise specified).

__all__ = ['Direction']

# Cell
class Direction:
    def __init__(self, directions=['NORTH', 'EAST', 'SOUTH', 'WEST'], idx=None):
        if idx is None:
            idx = np.random.choice(np.arange(4))
        self.directions = directions
        self.max_idx = len(directions)-1
        self.f = self.directions[idx]

    def get_idx(self):
        return self.directions.index(self.f)

    def left(self):
        idx = self.get_idx()
        new_idx = idx-1 if idx>=1 else self.max_idx
        return self.__class__(idx=new_idx)

    def right(self):
        idx = self.get_idx()
        new_idx = idx+1 if idx<=2 else 0
        return self.__class__(idx=new_idx)

    def __repr__(self):
        return self.f